### ISSUE TITLE
bounding box exceeds image dimensions

### ISSUE THREAD

**Issue by yyhlvdl** [avivga/audio-visual-speech-enhancement#2]
@avivga thanks for your work. Now, I begin to study audio-visual-speech-enhancement, and I use your code. And some problems have happend.

When I run preprocess, some files cann't be preprocess, like:

failed to preprocess (AudioVisualEntry(speaker_id='s7', audio_path='GRIDMP4/s7/audio/swwo6n.wav', video_path='GRIDMP4/s7/video/swwo6n.mp4'), 'noise100/n15.wav') (bounding box exceeds image dimensions)

Can you give me some advice? Thanks.

**Comment by avivga** [comment]
The preprocessor tries to crop the mouth region of the face using a bounding box of the specified fixed size (128x128 by default). The exception you describe is raised when it is impossible to crop and center a bounding box of the specified size around the mouth region without exceeding the entire image dimensions. 

You might try to adapt the bounding box size according to your input video resolution.
