### ISSUE TITLE
'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ivllm** [avivga/audio-visual-speech-enhancement#6]
Hello, I had a problem using this code.

I downloaded GRIDcorpus dataset in https://zenodo.org/record/3625687#.X5EQpCb_yUk
then, I organized the directory structure according to your guide in readme

execution command:
python speech_enhancer.py --base_dir outputdata preprocess --data_name outputdata --dataset_dir /home/dataset/dataset/GRIDcorpus --noise_dirs /home/dataset/noise

error message:
failed to preprocess (AudioVisualEntry(speaker_id='s2', audio_path='/home/dataset/dataset/GRIDcorpus/s2/audio/bbaf1n.wav', video_path='/home/dataset/dataset/GRIDcorpus/s2/video/bbaf1n.mpg'), '/home/dataset/noise/bbafzs.wav') ('float' object cannot be interpreted as an integer)

Do I need Additional preprocesses before the preprocess of speech_enhancer.py?

**Comment by avivga** [comment]
It would be quite difficult to figure out the problem without the entire stacktrace.
Do you process audio signals at 16kHz and corresponding video signals at 25fps? If not, try resampling the inputs using ffmpeg.

**Comment by ivllm** [comment]
preprocessing data...
preprocessing sample: /home/dataset/dataset/GRIDcorpus/s2/video/bbaf1n.mpg, /home/dataset/dataset/GRIDcorpus/s2/audio/bbaf1n.wav, /home/dataset/noise/bbafzs.wav...
preprocessing /home/dataset/dataset/GRIDcorpus/s2/video/bbaf1n.mpg
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-31
OMP: Info #214: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #156: KMP_AFFINITY: 32 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #285: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #285: KMP_AFFINITY: topology layer "L3 cache" is equivalent to "socket".
OMP: Info #285: KMP_AFFINITY: topology layer "L2 cache" is equivalent to "core".
OMP: Info #285: KMP_AFFINITY: topology layer "L1 cache" is equivalent to "core".
OMP: Info #191: KMP_AFFINITY: 2 sockets x 8 cores/socket x 2 threads/core (16 total cores)
OMP: Info #216: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 16 maps to socket 0 core 0 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to socket 0 core 1 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 17 maps to socket 0 core 1 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to socket 0 core 2 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 18 maps to socket 0 core 2 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to socket 0 core 3 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 19 maps to socket 0 core 3 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to socket 0 core 4 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 20 maps to socket 0 core 4 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to socket 0 core 5 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 21 maps to socket 0 core 5 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to socket 0 core 6 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 22 maps to socket 0 core 6 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to socket 0 core 7 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 23 maps to socket 0 core 7 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to socket 1 core 0 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 24 maps to socket 1 core 0 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to socket 1 core 1 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 25 maps to socket 1 core 1 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to socket 1 core 2 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 26 maps to socket 1 core 2 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to socket 1 core 3 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 27 maps to socket 1 core 3 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 12 maps to socket 1 core 4 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 28 maps to socket 1 core 4 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 13 maps to socket 1 core 5 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 29 maps to socket 1 core 5 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 14 maps to socket 1 core 6 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 30 maps to socket 1 core 6 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 15 maps to socket 1 core 7 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to socket 1 core 7 thread 1 
OMP: Info #252: KMP_AFFINITY: pid 142125 tid 142125 thread 0 bound to OS proc set 0
failed to preprocess (AudioVisualEntry(speaker_id='s2', audio_path='/home/dataset/dataset/GRIDcorpus/s2/audio/bbaf1n.wav', video_path='/home/dataset/dataset/GRIDcorpus/s2/video/bbaf1n.mpg'), '/home/dataset/noise/bbafzs.wav') ('float' object cannot be interpreted as an integer)

I used the dataset that I downloaded from the website. https://zenodo.org/record/3625687#.X5EQpCb_yUk
You mean I have to process the dataset into 16 kHz and 25 fps and then run "python speech_enhancer.py --base_dir outputdata preprocess --data_name outputdata --dataset_dir /home/dataset/dataset/GRIDcorpus --noise_dirs /home/dataset/noise", right?

If possible, could you share the conversion code using ffmpeg you used before?

**Comment by ivllm** [comment]
I tried conversion as below using ffmpeg, but got the same error ('float' object cannot be interpreted as an integer)
ffmpeg -i bbaf3p.wav -b:a 16k -f wav bbaf3p_2.wav     //to 16khz
ffmpeg -i bbaf1n.mpg -r 25 -f mp4 bbaf1n_2.mp4       //to 25fps

Can you give me any helpful opinion..?

**Comment by avivga** [comment]
In order to obtain a more informative stacktrace you might want to disable the multi-threaded preprocessing in data_processor.py [line 195] and preprocess the samples in a synchronized fashion. It should improve debuggability.

**Comment by ivllm** [comment]
Thank you for your answer. I found the answer through this link.
https://stackoverflow.com/questions/54778001/how-to-to-tackle-overflowerror-cannot-convert-float-infinity-to-integer

get_length() function to obtain the number of frame did not work properly due to the imageio version update

**Comment by ylyinzju** [comment]
how to figure this question?

**Comment by ivllm** [comment]
@ylyinzju What question do you mean?

**Comment by ylyinzju** [comment]
I also meet this "'float' object cannot be interpreted as an integer", but i didn't find the get_length() function.  which version of python you used? python2 or python3?

**Comment by ylyinzju** [comment]
> 
> 
> @ylyinzju What question do you mean?

oh, i reslove it ,  thanks

**Comment by ylyinzju** [comment]
> 
> 
> Thank you for your answer. I found the answer through this link.
> https://stackoverflow.com/questions/54778001/how-to-to-tackle-overflowerror-cannot-convert-float-infinity-to-integer
> 
> get_length() function to obtain the number of frame did not work properly due to the imageio version update

I resolve it , thanks

**Comment by ivllm** [comment]
@ylyinzju Have a good day! :)
